services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7000:8080"
    volumes:
      - db:/usr/src/app/db:z
      - ./docker-relay-config.toml:/usr/src/app/config.toml
    environment:
      - RUST_LOG=debug

volumes:
  db: